In [40]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
from Univariate import Univariate

dataset = pd.read_csv("Placement.csv")

quan, qual = Univariate.quanQual(dataset)

In [4]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [6]:
dataset['ssc_p'].mean()

np.float64(67.30339534883721)

In [8]:
dataset['ssc_p'].mode()[0]

np.float64(62.0)

In [9]:
dataset['ssc_p'].median()

67.0

In [11]:
dataset.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [13]:
descriptive = pd.DataFrame()
descriptive

Empty DataFrame
Columns: []
Index: []

In [17]:
descriptive = pd.DataFrame(index=['Mean','Median','Mode'])
descriptive

Empty DataFrame
Columns: []
Index: [Mean, Meadian, Mode]

In [20]:
descriptive = pd.DataFrame(index=['Mean','Median','Mode'], columns=quan)
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [23]:
for column in quan:
    descriptive[column]['Mean'] = dataset[column].mean()
    descriptive[column]['Median'] = dataset[column].median()
    descriptive[column]['Mode'] = dataset[column].mode()[0]

descriptive

C:\Users\z030703\AppData\Local\Temp\ipykernel_12600\2385051552.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[column]['Mean'] = dataset[column].mean()
C:\Users\z030703\AppData\Local\Temp\ipykernel_12600\2385051552.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[column]['Median'] = dataset[column].median()
C:\Users\z030703\AppData\Local\Temp\ipykernel_12600\2385051552.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[column]['Mode'] = dataset[column].mode()[0]
C:\Users\z030703\AppData\Local\Temp\ipykernel_12600\2385051552.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[column]['Mean'] = dataset[column].mean()
C:\Users\z030703\AppData\Local\Temp\ipykernel_12600\2385051552.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[column]['Median'] = dataset[column].median()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0

In [31]:
import numpy as np

np.percentile(dataset['ssc_p'],25) #25th percentile
# first 25% of students scored below 60.5 in ssc_p

np.float64(60.599999999999994)

In [33]:
descriptive = pd.DataFrame(index=['Mean','Median','Mode','Q1:25%','Q2:50%','Q3:75%','99%','Q4:100%'], columns=quan)
descriptive

        sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean      NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median    NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode      NaN   NaN   NaN      NaN     NaN   NaN    NaN
Q1:25%    NaN   NaN   NaN      NaN     NaN   NaN    NaN
Q2:50%    NaN   NaN   NaN      NaN     NaN   NaN    NaN
Q3:75%    NaN   NaN   NaN      NaN     NaN   NaN    NaN
99%       NaN   NaN   NaN      NaN     NaN   NaN    NaN
Q4:100%   NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [41]:
for column in quan:
    descriptive[column]['Mean'] = dataset[column].mean()
    descriptive[column]['Median'] = dataset[column].median()
    descriptive[column]['Mode'] = dataset[column].mode()[0]
    descriptive[column]['Q1:25%'] = dataset.describe()[column]['25%']
    descriptive[column]['Q2:50%'] = dataset.describe()[column]['50%']
    descriptive[column]['Q3:75%'] = dataset.describe()[column]['75%']
    descriptive[column]['99%'] = np.percentile(dataset[column],99)
    descriptive[column]['Q4:100%'] = dataset.describe()[column]['max']

descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.86,83.86,97.0,76.1142,NaN
Q4:100%,215.0,89.4,97.7,91.0,98.0,77.89,940000.0